// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: command_msg.proto

#include "command_msg.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace msg {
namespace proto {
PROTOBUF_CONSTEXPR CommandMsg::CommandMsg(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.args_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.msg_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.command_)*/0} {}
struct CommandMsgDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CommandMsgDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~CommandMsgDefaultTypeInternal() {}
  union {
    CommandMsg _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CommandMsgDefaultTypeInternal _CommandMsg_default_instance_;
}  // namespace proto
}  // namespace msg
static ::_pb::Metadata file_level_metadata_command_5fmsg_2eproto[1];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_command_5fmsg_2eproto[1];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_command_5fmsg_2eproto = nullptr;

const uint32_t TableStruct_command_5fmsg_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::msg::proto::CommandMsg, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::msg::proto::CommandMsg, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::msg::proto::CommandMsg, _impl_.command_),
  PROTOBUF_FIELD_OFFSET(::msg::proto::CommandMsg, _impl_.args_),
  PROTOBUF_FIELD_OFFSET(::msg::proto::CommandMsg, _impl_.msg_),
  2,
  0,
  1,
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 9, -1, sizeof(::msg::proto::CommandMsg)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::msg::proto::_CommandMsg_default_instance_._instance,
};

const char descriptor_table_protodef_command_5fmsg_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\021command_msg.proto\022\tmsg.proto\"P\n\nComman"
  "dMsg\022\'\n\007command\030\001 \002(\0162\026.msg.proto.Comman"
  "dType\022\014\n\004args\030\002 \001(\014\022\013\n\003msg\030\003 \001(\014*I\n\013Comm"
  "andType\022\016\n\nCOMMAND_LS\020\000\022\024\n\020COMMAND_DOWNF"
  "ILE\020\001\022\024\n\020COMMAND_ERRORMSG\020\002B\002H\002"
  ;
static ::_pbi::once_flag descriptor_table_command_5fmsg_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_command_5fmsg_2eproto = {
    false, false, 191, descriptor_table_protodef_command_5fmsg_2eproto,
    "command_msg.proto",
    &descriptor_table_command_5fmsg_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_command_5fmsg_2eproto::offsets,
    file_level_metadata_command_5fmsg_2eproto, file_level_enum_descriptors_command_5fmsg_2eproto,
    file_level_service_descriptors_command_5fmsg_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_command_5fmsg_2eproto_getter() {
  return &descriptor_table_command_5fmsg_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_command_5fmsg_2eproto(&descriptor_table_command_5fmsg_2eproto);
namespace msg {
namespace proto {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* CommandType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_command_5fmsg_2eproto);
  return file_level_enum_descriptors_command_5fmsg_2eproto[0];
}
bool CommandType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}


// ===================================================================

class CommandMsg::_Internal {
 public:
  using HasBits = decltype(std::declval<CommandMsg>()._impl_._has_bits_);
  static void set_has_command(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_args(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_msg(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000004) ^ 0x00000004) != 0;
  }
};

CommandMsg::CommandMsg(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:msg.proto.CommandMsg)
}
CommandMsg::CommandMsg(const CommandMsg& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  CommandMsg* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.args_){}
    , decltype(_impl_.msg_){}
    , decltype(_impl_.command_){}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.args_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.args_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_args()) {
    _this->_impl_.args_.Set(from._internal_args(), 
      _this->GetArenaForAllocation());
  }
  _impl_.msg_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.msg_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_msg()) {
    _this->_impl_.msg_.Set(from._internal_msg(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.command_ = from._impl_.command_;
  // @@protoc_insertion_point(copy_constructor:msg.proto.CommandMsg)
}

inline void CommandMsg::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.args_){}
    , decltype(_impl_.msg_){}
    , decltype(_impl_.command_){0}
  };
  _impl_.args_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.args_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.msg_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.msg_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

CommandMsg::~CommandMsg() {
  // @@protoc_insertion_point(destructor:msg.proto.CommandMsg)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void CommandMsg::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.args_.Destroy();
  _impl_.msg_.Destroy();
}

void CommandMsg::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void CommandMsg::InternalSwap(CommandMsg* other) {
  using std::swap;
  GetReflection()->Swap(this, other);}

::PROTOBUF_NAMESPACE_ID::Metadata CommandMsg::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_command_5fmsg_2eproto_getter, &descriptor_table_command_5fmsg_2eproto_once,
      file_level_metadata_command_5fmsg_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
}  // namespace msg
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::msg::proto::CommandMsg*
Arena::CreateMaybeMessage< ::msg::proto::CommandMsg >(Arena* arena) {
  return Arena::CreateMessageInternal< ::msg::proto::CommandMsg >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
