// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fileinfos_msg.proto

#include "fileinfos_msg.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace msg {
namespace proto {
PROTOBUF_CONSTEXPR fileInfo::fileInfo(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.name_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.size_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.last_write_time_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}} {}
struct fileInfoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR fileInfoDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~fileInfoDefaultTypeInternal() {}
  union {
    fileInfo _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 fileInfoDefaultTypeInternal _fileInfo_default_instance_;
PROTOBUF_CONSTEXPR FileInfoMsg::FileInfoMsg(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.fileinfos_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct FileInfoMsgDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FileInfoMsgDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~FileInfoMsgDefaultTypeInternal() {}
  union {
    FileInfoMsg _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FileInfoMsgDefaultTypeInternal _FileInfoMsg_default_instance_;
}  // namespace proto
}  // namespace msg
static ::_pb::Metadata file_level_metadata_fileinfos_5fmsg_2eproto[2];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_fileinfos_5fmsg_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_fileinfos_5fmsg_2eproto = nullptr;

const uint32_t TableStruct_fileinfos_5fmsg_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::msg::proto::fileInfo, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::msg::proto::fileInfo, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::msg::proto::fileInfo, _impl_.name_),
  PROTOBUF_FIELD_OFFSET(::msg::proto::fileInfo, _impl_.size_),
  PROTOBUF_FIELD_OFFSET(::msg::proto::fileInfo, _impl_.last_write_time_),
  0,
  1,
  2,
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::msg::proto::FileInfoMsg, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::msg::proto::FileInfoMsg, _impl_.fileinfos_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 9, -1, sizeof(::msg::proto::fileInfo)},
  { 12, -1, -1, sizeof(::msg::proto::FileInfoMsg)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::msg::proto::_fileInfo_default_instance_._instance,
  &::msg::proto::_FileInfoMsg_default_instance_._instance,
};

const char descriptor_table_protodef_fileinfos_5fmsg_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\023fileinfos_msg.proto\022\tmsg.proto\"\?\n\010file"
  "Info\022\014\n\004name\030\001 \002(\t\022\014\n\004size\030\002 \002(\t\022\027\n\017last"
  "_write_time\030\003 \002(\t\"5\n\013FileInfoMsg\022&\n\tfile"
  "infos\030\001 \003(\0132\023.msg.proto.fileInfoB\002H\002"
  ;
static ::_pbi::once_flag descriptor_table_fileinfos_5fmsg_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_fileinfos_5fmsg_2eproto = {
    false, false, 156, descriptor_table_protodef_fileinfos_5fmsg_2eproto,
    "fileinfos_msg.proto",
    &descriptor_table_fileinfos_5fmsg_2eproto_once, nullptr, 0, 2,
    schemas, file_default_instances, TableStruct_fileinfos_5fmsg_2eproto::offsets,
    file_level_metadata_fileinfos_5fmsg_2eproto, file_level_enum_descriptors_fileinfos_5fmsg_2eproto,
    file_level_service_descriptors_fileinfos_5fmsg_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_fileinfos_5fmsg_2eproto_getter() {
  return &descriptor_table_fileinfos_5fmsg_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_fileinfos_5fmsg_2eproto(&descriptor_table_fileinfos_5fmsg_2eproto);
namespace msg {
namespace proto {

// ===================================================================

class fileInfo::_Internal {
 public:
  using HasBits = decltype(std::declval<fileInfo>()._impl_._has_bits_);
  static void set_has_name(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_size(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_last_write_time(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000007) ^ 0x00000007) != 0;
  }
};

fileInfo::fileInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:msg.proto.fileInfo)
}
fileInfo::fileInfo(const fileInfo& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  fileInfo* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.name_){}
    , decltype(_impl_.size_){}
    , decltype(_impl_.last_write_time_){}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_name()) {
    _this->_impl_.name_.Set(from._internal_name(), 
      _this->GetArenaForAllocation());
  }
  _impl_.size_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.size_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_size()) {
    _this->_impl_.size_.Set(from._internal_size(), 
      _this->GetArenaForAllocation());
  }
  _impl_.last_write_time_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.last_write_time_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_last_write_time()) {
    _this->_impl_.last_write_time_.Set(from._internal_last_write_time(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:msg.proto.fileInfo)
}

inline void fileInfo::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.name_){}
    , decltype(_impl_.size_){}
    , decltype(_impl_.last_write_time_){}
  };
  _impl_.name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.size_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.size_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.last_write_time_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.last_write_time_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

fileInfo::~fileInfo() {
  // @@protoc_insertion_point(destructor:msg.proto.fileInfo)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void fileInfo::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.name_.Destroy();
  _impl_.size_.Destroy();
  _impl_.last_write_time_.Destroy();
}

void fileInfo::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void fileInfo::InternalSwap(fileInfo* other) {
  using std::swap;
  GetReflection()->Swap(this, other);}

::PROTOBUF_NAMESPACE_ID::Metadata fileInfo::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_fileinfos_5fmsg_2eproto_getter, &descriptor_table_fileinfos_5fmsg_2eproto_once,
      file_level_metadata_fileinfos_5fmsg_2eproto[0]);
}

// ===================================================================

class FileInfoMsg::_Internal {
 public:
};

FileInfoMsg::FileInfoMsg(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:msg.proto.FileInfoMsg)
}
FileInfoMsg::FileInfoMsg(const FileInfoMsg& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  FileInfoMsg* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.fileinfos_){from._impl_.fileinfos_}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:msg.proto.FileInfoMsg)
}

inline void FileInfoMsg::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.fileinfos_){arena}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

FileInfoMsg::~FileInfoMsg() {
  // @@protoc_insertion_point(destructor:msg.proto.FileInfoMsg)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void FileInfoMsg::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.fileinfos_.~RepeatedPtrField();
}

void FileInfoMsg::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void FileInfoMsg::InternalSwap(FileInfoMsg* other) {
  using std::swap;
  GetReflection()->Swap(this, other);}

::PROTOBUF_NAMESPACE_ID::Metadata FileInfoMsg::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_fileinfos_5fmsg_2eproto_getter, &descriptor_table_fileinfos_5fmsg_2eproto_once,
      file_level_metadata_fileinfos_5fmsg_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
}  // namespace msg
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::msg::proto::fileInfo*
Arena::CreateMaybeMessage< ::msg::proto::fileInfo >(Arena* arena) {
  return Arena::CreateMessageInternal< ::msg::proto::fileInfo >(arena);
}
template<> PROTOBUF_NOINLINE ::msg::proto::FileInfoMsg*
Arena::CreateMaybeMessage< ::msg::proto::FileInfoMsg >(Arena* arena) {
  return Arena::CreateMessageInternal< ::msg::proto::FileInfoMsg >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
